# Site settings
title: Bert de Vries
email: bdevries _at_ ieee _dot_ org
description: > # this means to ignore newlines until "baseurl:"
  I'm a Principal Scientist at hearing aid manufacturer GN ReSound and a (part-time) Professor at Eindhoven University of technology (TU/e). At TU/e, I lead a research team that works on (Bayesian) machine learning methods to support the design of hearing aid algorithms. Specific topics of interest probabilistic reasoning, signal processing, computational neuroscience and factor graphs. I also teach a graduate class on Adaptive Information Processing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bertdv.nl" # the base hostname & protocol for your site
twitter_username: bertdv0
github_username: bertdv
linkedin_username: bertdv

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Professor"
excerpt_separator: "<!--more-->"

# plugins
gems:
  - jekyll-sitemap
